### PR TITLE
Update to 1.20.1

### PR DESCRIPTION
**Pull request by Mrbysco**

### CODE REVIEW

**Comment by generikb** [comment]
Hey @mezz would you check out MrBysco's 1.20.1 update PR and see if it's worthy to update to CF?  ItemZoom (believe it or not) is one of my favorite mods out there, it's a must-have for all my modpacks!  I even add it to other people's packs when I play! :)

Thanks so much!

Genny

**Comment by mezz** [comment]
Sorry for the delay. Thank you for contributing!

**Comment by mezz** [comment]
Thanks for your support @generikb ! You can find the new version here: https://www.curseforge.com/minecraft/mc-mods/itemzoom/files/5043628

**Comment by generikb** [comment]
fantastic! Thanks so much!

**Pull request merged**
